# Generated by Django 6.0.3 on 2026-07-17 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="update_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
